[CmdletBinding()]
param(
    # Where the work copy is created. Must not be inside this repository and
    # must not be the original BuildWorkspace.
    [Parameter(Mandatory)] [string]$Workspace,
    # The BuildWorkspace the WiiCompiled installer created from your own disc.
    [string]$BuildWorkspace = "$env:APPDATA\CT-MKWII\Recomp\Install\BuildWorkspace",
    [string]$PatchDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'patches'),
    # Re-apply the patches onto an existing work copy without copying again.
    [switch]$PatchOnly
)

# Creates the Android work copy: a copy of the user's own BuildWorkspace (the
# translated game, runtime, aurora, project files) without the PC build
# directories, plus this repository's patches. The original installation is
# only read. No game data is copied by this script: generated/ holds the
# translated code, which stays on the user's machine and never enters the repo.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3.0

$Workspace = [IO.Path]::GetFullPath($Workspace)
$BuildWorkspace = [IO.Path]::GetFullPath($BuildWorkspace)
if ($Workspace.TrimEnd('\') -ieq $BuildWorkspace.TrimEnd('\')) {
    throw 'The work copy must not be the original BuildWorkspace.'
}
$repoRoot = [IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
if ($Workspace.StartsWith($repoRoot, [StringComparison]::OrdinalIgnoreCase)) {
    throw "The work copy must not live inside this repository ($repoRoot): it contains translated game code."
}
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    throw 'git is required (git apply applies the patches).'
}

if (-not $PatchOnly) {
    foreach ($required in @('generated', 'runtime', 'aurora-main', 'projects', 'LocalBuild.ps1')) {
        if (-not (Test-Path -LiteralPath (Join-Path $BuildWorkspace $required))) {
            throw "Not a WiiCompiled BuildWorkspace (missing $required): $BuildWorkspace"
        }
    }
    if (Test-Path -LiteralPath $Workspace) {
        throw "The work copy already exists: $Workspace. Remove it or use -PatchOnly."
    }
    Write-Host "Copying $BuildWorkspace -> $Workspace (build directories excluded)..."
    # build/ and native-build/ hold CMake caches with absolute paths of the
    # original installation; build/mods is regenerated by the translator step.
    & robocopy $BuildWorkspace $Workspace /E /NFL /NDL /NJH /NJS /NP /XD build native-build | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed with exit code $LASTEXITCODE" }
}

# Fix AA: 1 MiB host stack per guest fiber. Newer WiiCompiled
# versions already ship this line, the pinned commit does not; a text replacement
# works on both where a patch hunk could not. Runs before 0003, whose
# fiber_manager.cpp hunk expects the 1 MiB line.
$fiberManager = Join-Path $Workspace 'runtime\src\fiber_manager.cpp'
if (Test-Path -LiteralPath $fiberManager) {
    $text = [IO.File]::ReadAllText($fiberManager)
    if ($text.Contains('constexpr size_t kHostStackSize = 64 * 1024;')) {
        [IO.File]::WriteAllText($fiberManager, $text.Replace('constexpr size_t kHostStackSize = 64 * 1024;', 'constexpr size_t kHostStackSize = 1024 * 1024;'))
        Write-Host 'Applied Fix AA (fiber host stack 1 MiB)'
    }
}

# 0001 targets the BuildWorkspace as shipped; 0003 targets 0001's result (plus Fix AA).
# 0002 is for the translator source tree, see Regenerate-AndroidTranslation.ps1.
$patches = @('0001-android-buildworkspace.patch', '0003-quest-adreno-workaround.patch')
Push-Location $Workspace
try {
    foreach ($patch in $patches) {
        $path = Join-Path $PatchDirectory $patch
        if (-not (Test-Path -LiteralPath $path)) { throw "Patch not found: $path" }
        # --ignore-whitespace: the installation ships CRLF, the patches are LF.
        & git apply --check --ignore-whitespace $path
        if ($LASTEXITCODE -ne 0) {
            throw "$patch does not apply cleanly. Either it is already applied (use git apply --reverse --check to see) or the installed WiiCompiled version differs from the one the patch was made against."
        }
        & git apply --ignore-whitespace $path
        if ($LASTEXITCODE -ne 0) { throw "git apply failed for $patch" }
        Write-Host "Applied $patch"
    }
} finally {
    Pop-Location
}

Write-Host ''
Write-Host "Work copy ready: $Workspace"
Write-Host 'Next: tools\Regenerate-AndroidTranslation.ps1, then tools\Build-Quest.ps1'
